local current = lfs.currentdir()
print('core init start')
dofile(current.."/core/coreexdata.lua")
dofile(current.."/core/coredata.lua")
print('core init start 2')
dofile(current.."/core/corecache.lua")
print('core init start 3')
dofile(current.."/core/helper.lua")
print('core init start 4')
dofile(current.."/core/nethelper.lua")
print(current..'core init start 5')
dofile(current..'/core/ZZBase64.lua')
print(current..'core init start 6')
dofile(current..'/core/coremath.lua')
print('core init end')